### ISSUE TITLE
Update mouse cursor

### ISSUE THREAD

**Issue by audreygentili** [GnuCodingStudio/GameZam002-still-steal#8]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

- The experience of the mouse player is not optimal and could be improve.

---

## **Describe the solution you'd like**

We could change the mouse cursor to fit with the game design.

---

## **Describe alternatives you've considered**

👍 

---

### **Additional context**

👍

**Comment by olivierperez** [comment]
Packs from Kenney (don't forget to add the reference in Credits)
- https://www.kenney.nl/assets/cursor-pack
- https://www.kenney.nl/assets/cursor-pixel-pack

**Comment by AnthoMarquet** [comment]
https://docs.godotengine.org/en/stable/tutorials/inputs/custom_mouse_cursor.html

**Comment by AnthoMarquet** [comment]
Vidéo tuto : 
https://www.youtube.com/watch?v=zClZVTguhN0
